### ISSUE TITLE
gridmanager-vue中的刷新方法怎么用？

### ISSUE THREAD

**Issue by cuitwangshicheng** [baukh789/GridManager-Vue#1]
如题，主要是不知道vue版本中怎么去获取js版本中的gridmanager对象

**Comment by cuitwangshicheng** [comment]
那个option中的唯一值怎么用？

**Comment by baukh789** [comment]
与[gridmanager](https://github.com/baukh789/GridManager)方式相同

```
table.GM('refreshGrid')
```

**Comment by baukh789** [comment]
从 v1.0.22开始，支持通过`this.$gridManager`的方式进行操作GM对像。
