### ISSUE TITLE
表头宽度拖拽，无法复位

### ISSUE THREAD

**Issue by XLearner** [baukh789/GridManager-Vue#11]
对表头的宽度进行拖拽调整的时候，横向滚动条只会越拖越长，而不能将列宽调小。

**Comment by XLearner** [comment]
![初始状态](https://user-images.githubusercontent.com/26158725/81464969-de8e3500-91f8-11ea-95ea-262313d90df1.png)
![拖动后](https://user-images.githubusercontent.com/26158725/81464971-e3eb7f80-91f8-11ea-85f8-de399682a29b.png)

**Comment by baukh789** [comment]
这个是宽度调整的现有交互，你所期望的交互方式后续会进行调整



---原始邮件---
发件人: "XLearner"<notifications@github.com&gt;
发送时间: 2020年5月9日(周六) 中午1:22
收件人: "baukh789/GridManager-Vue"<GridManager-Vue@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [baukh789/GridManager-Vue] 表头宽度拖拽，无法复位 (#11)

**Comment by XLearner** [comment]
> 这个是宽度调整的现有交互，你所期望的交互方式后续会进行调整
> […](#)
> ---原始邮件--- 发件人: "XLearner"<notifications@github.com&gt; 发送时间: 2020年5月9日(周六) 中午1:22 收件人: "baukh789/GridManager-Vue"<GridManager-Vue@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [baukh789/GridManager-Vue] 表头宽度拖拽，无法复位 (#11) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的谢谢😂你的这个组件很棒，期待后续更新。

**Comment by baukh789** [comment]
谢谢，喜欢的话就推荐给他人吧。
grid-manager-vue的核心库在这里: https://github.com/baukh789/GridManager， 支持Angular-1.x， Vue2.0, React三套框架。
关于更新: [version log](https://gridmanager.lovejavascript.com/version/index.html)
