### ISSUE TITLE
右键菜单问题

### ISSUE THREAD

**Issue by pandizhubp** [baukh789/GridManager-Vue#15]
你好，我想请问下，表格右键功能菜单 可以取消其中某一个或者多个菜单按钮么？

**Comment by baukh789** [comment]
可以的，参考[API menuHandler](https://gridmanager.lovejavascript.com/api/index.html#menuHandler)

**Comment by pandizhubp** [comment]
大神 您好，设置好 checkboxConfig 中的useRowCheck 为 true后可以单击 选中行 但是我想 单击某行选中行 其他行都取消选中，点击checkbox的时候多选，我看了全部的api 也没有找到合适的办法，咨询下作者您

**Comment by baukh789** [comment]
可以通过在事件[checkedBefore](https://gridmanager.lovejavascript.com/api/index.html#checkedBefore)中进行处理。
