### ISSUE TITLE
[ GridManager-Vue]如何动态调整columnData

### ISSUE THREAD

**Issue by a-l-o-n-g** [baukh789/GridManager-Vue#27]
demo中都是静态的数据直接放在了columnData中，我这边的需求是需要先把columnData请求回来后再去请求数据，试着把请求的列配置数据通过this.gridOption.columnData赋值，直接报错columnData invalid；应该是初始化的时候没有找到列数据，应该有个先后顺序，我这边应该如何处理？

**Comment by baukh789** [comment]
初始化请求时，columnData返回后再进行实例化。后续columnData再变化时，使用renderGrid进行修改。

**Comment by a-l-o-n-g** [comment]
` <grid-manager  :option="gridOption" :callback="callback" ref="grid"></grid-manager>`
这个组件已经写在了`<template>`中，这样如何实例化？

**Comment by baukh789** [comment]
在渲染<template>前获取columnData数据

**Comment by a-l-o-n-g** [comment]
你好，请问下嵌套表头是不支持固定列功能吗？

**Comment by baukh789** [comment]
> 你好，请问下嵌套表头是不支持固定列功能吗？

是的，这两个功能在当前版本是互斥的

**Comment by a-l-o-n-g** [comment]
好的，谢谢
