### ISSUE TITLE
'tenantRelateShop' is not defined 

### ISSUE THREAD

**Issue by leefreeF** [baukh789/GridManager-Vue#6]
![image](https://user-images.githubusercontent.com/32056701/50150727-c82cc400-02f9-11e9-8072-d9914d486bf7.png)

按照样例复制会报错

**Comment by leefreeF** [comment]
而且初始化的时候  表头都聚到了一起  是什么情况呢
![image](https://user-images.githubusercontent.com/32056701/50154455-5148f880-0304-11e9-9644-a119192810bd.png)

**Comment by baukh789** [comment]
你需要先解决undefined的问题
至于表头聚到了一起，可能也是由于这个问题导致的。
