### ISSUE TITLE
老哥，能不能做个多表列拖动的方法啊

### ISSUE THREAD

**Issue by RuohanXiao** [baukh789/GridManager-Vue#9]
比如将表1的某一列拖动到表2，形成新的一列。
我看了国内外好多组件，没有一个支持这种形式的

**Comment by baukh789** [comment]
这个功能，还真没考虑过。
这个看上去已经不单单是表格组件的事情了，不过我有个思你可以尝试下:
- 在表1和表2中都包含开启拖拽的列
- 在表1中通过拖拽的回调事件进行监听当前的鼠标位置
- 当到达表2的某个位置时，将表1中的这一列隐藏，将表2中对应的列显示

具体效果我没有尝试，这只是一个思路。
